### ISSUE TITLE
main.py执行的时候闪退是什么原因

### ISSUE THREAD

**Issue by FLoutione** [thomas-yanxin/OXiaoPeng#6]
用PowerShell执行main.py时，出现 File "D:\Google_Downlode\OXiaoPeng-master\main.py", line 12, in <module> import clueai
ModuleNotFoundError: No module named 'clueai'
执行main-chatgpt.py时，出现 File "D:\Google_Downlode\OXiaoPeng-master\main-chatgpt.py", line 5, in <module> from revChatGPT.Official import Chatbot
ModuleNotFoundError: No module named 'revChatGPT.Official'
不知道是哪里的问题

**Comment by thomas-yanxin** [comment]
**原因**：
抱歉哈，之前版本的requirements.txt里没有包含clueai和revChatGPT这两个python库，因此导致了您执行出现了问题。
**解决方案**：
目前OXiaoPeng代码已更新，请clone最新的OXiaoPeng仓库，并执行`pip install -r requirements.txt`安装所有的依赖库。

十分抱歉哈！有问题请继续交流。
